# Limpieza de datos

Cargamos la base

In [1]:
# Scientific libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Pandas options
pd.options.display.max_columns = None

In [ ]:
# first option to read the dataset
df_consolidado = pd.read_csv('data/1-bronce/Consolidado-SIMAT-2017-2021.csv', index_col=0)

In [2]:
# Second option to read the dataset
chunk = pd.read_csv('data/1-bronce/Consolidado-SIMAT-2017-2021.csv', chunksize = 10000)
df_consolidado = pd.concat(chunk)

In [3]:
df_consolidado.head(2)

Unnamed: 0  ANO_INF   CODIGO_DANE  CODIGO_DANE_SEDE  TIPO_DOCUMENTO  \
0           0     2017  111001000078      111001000078               2   
1           1     2017  111001000078      111001014834               3   

  NRO_DOCUMENTO APELLIDO1 APELLIDO2  NOMBRE1    NOMBRE2 DIRECCION_RESIDENCIA  \
0   00010803853      CRUZ      CANO    LAURA  VALENTINA     CL 69 A 105 F 67   
1      05057637     NAVAS  GONZALEZ  SUJEIBY  VALENTINA    CL 34 SUR 40 A 51   

   RES_DEPTO  RES_MUN  ESTRATO SISBEN FECHA_NACIMIENTO GENERO  POB_VICT_CONF  \
0         11        1        2    ,01         1/8/2000      F              9   
1         11        1        3               6/13/2012      F              9   

  DPTO_EXP MUN_EXP PROVIENE_SECTOR_PRIV PROVIENE_OTR_MUN  TIPO_DISCAPACIDAD  \
0                                     N                N                 99   
1                                     N                N                 99   

   CAP_EXC  CODIGO_ETNIA  CODIGO_JORNADA  CARACTER  CODIGO_ESPECIALIDAD  \
0        9             0               6       1.0                    5   
1        9             0               3       0.0                    0   

   CODIGO_GRADO  CODIGO_METODOLOGIA REPITENTE  SIT_ACAD_ANIO_ANT  \
0            10                   1         N                  1   
1             0                   1         N                  0   

   CON_ALUM_ANIO_ANT ZONA_RESI_ALU VALORACION1 VALORACION2 CODIGO_INTERNADO  \
0                9.0             1                                        3   
1                9.0             1                                        3   

   EDAD  NIVEL DIR_NUM_LOCALIDAD  DIR_LOCALIDAD  
0    17      4                16  PUENTE ARANDA  
1     4      1                16  PUENTE ARANDA

## Parte I : Santiago

cols_santiago = ['CODIGO_DANE', 'CODIGO_DANE_SEDE', 'TIPO_DOCUMENTO', 'NRO_DOCUMENTO', 'APELLIDO1', 'APELLIDO2', 'NOMBRE1', 'NOMBRE2', 'DIRECCION_RESIDENCIA']



In [4]:
# Convierte a String NRO_DOCUMENTO Y Direccion
df_consolidado['NRO_DOCUMENTO'] = df_consolidado['NRO_DOCUMENTO'].astype(str)

In [5]:
df_consolidado['DIRECCION_RESIDENCIA'] = df_consolidado['DIRECCION_RESIDENCIA'].astype(str)

In [ ]:
# Esta linea no corrió.. mataba el kernel de una -> omitida 
df_consolidado.drop(['APELLIDO1', 'APELLIDO2', 'NOMBRE1', 'NOMBRE2'], inplace=True, axis=1)

In [6]:
# Reemplaza con strings de acuerdo a diccionario. Mejor para graficas.
tipo_documento_dict = {
    1 : 'Cédula de Ciudadanía',
    2 : 'Tarjeta de Identidad',
    3 : 'Cédula de Extranjería ',
    5 : 'Registro Civil de Nacimiento',
    6 : 'Número de Identificación Personal (NIP)',
    7 : 'Número Único de Identificación Personal (NUIP)',
    8 : 'Número de Identificación establecido por la Secretaría de Educación',
    9 : 'Certificado Cabildo',                                                                                                         
    10: 'Permiso Especial de Permanencia',
    11: 'Visa',
    12: 'Tarjeta de movilidad fronteriza'
}
df_consolidado['NOMBRE_TIPO_DOCUMENTO'] = df_consolidado['TIPO_DOCUMENTO'].replace(tipo_documento_dict)
df_consolidado.insert(4, 'NOMBRE_TIPO_DOCUMENTO', df_consolidado.pop('NOMBRE_TIPO_DOCUMENTO'))

## Parte II: Juan

cols_juan = ['PROVIENE_SECTOR_PRIV', 'PROVIENE_OTR_MUN', 'TIPO_DISCAPACIDAD', 'CAP_EXC', 'CODIGO_ETNIA', 'CODIGO_JORNADA', 'CARACTER', 'CODIGO_ESPECIALIDAD', 'CODIGO_GRADO'] 


Exploración inicial de los datos

In [7]:
cols_juan = ['PROVIENE_SECTOR_PRIV', 'PROVIENE_OTR_MUN', 'TIPO_DISCAPACIDAD', 'CAP_EXC', 'CODIGO_ETNIA', 'CODIGO_JORNADA', 'CARACTER', 'CODIGO_ESPECIALIDAD', 'CODIGO_GRADO']

In [8]:
# Observamos los tipos de datos. Por un análisis exploratorio vemos que no hay vacíos.
# Codigo Etnia: Valores raros = 999, 998.
# CARACTER llega en tipo float.
for col in cols_juan:
    print(df_consolidado[col].unique() , str(col), df_consolidado[col].isnull().sum())

['N' 'S'] PROVIENE_SECTOR_PRIV 0
['N' 'S'] PROVIENE_OTR_MUN 0
[99  7  8 10 18 15 13 11  3  4 19 17 14  6 12  1  2  9  5 16] TIPO_DISCAPACIDAD 0
[ 9  4  1  3  2  5  6  7 11 10] CAP_EXC 0
[  0  46  49 200  75  97  19 999  83   1  45  26   4  29  74  53  44  77
  12  34  95  80   9  20  10  42  73  72  99  71  52   7  47 100  27  17
  15  25   5  14  31  66  70  28   2  48 400  22  18   6  57  64   3  65
  13 101  33  32  67   8  35 998  16  50  23  37  56  11  58  51  85  96
  86  62  40  30  54  38  82  90  36  43  21  61  24  92  81  55  68  60
  94 107  69 102  39  59  79  93  84  98 109  76] CODIGO_ETNIA 0
[6 3 2 4 1 5] CODIGO_JORNADA 0
[1. 0. 2.] CARACTER 0
[ 5  0  6  8  9  7 10] CODIGO_ESPECIALIDAD 0
[10  0  3 -1  9  7 11  8  6  5  2  4  1 99 25 26 23 24 22 -2 21 12 13] CODIGO_GRADO 0


In [9]:
# Al parecer los códigos extraños de Etnia solo son datos atípicos. Nos dice que CARACTER es int, lo cual es extraño.
for col in cols_juan:
    print(df_consolidado[col].value_counts())

N    3887182
S     515763
Name: PROVIENE_SECTOR_PRIV, dtype: int64
N    4347218
S      55727
Name: PROVIENE_OTR_MUN, dtype: int64
99    4306354
8       60546
10       7687
15       6260
18       4475
7        4084
13       3137
3        2105
17       2060
11       2037
12       1933
4         939
19        915
9         168
14         95
1          51
2          50
6          21
5          21
16          7
Name: TIPO_DISCAPACIDAD, dtype: int64
9     4396777
4        2370
1        1357
3         884
5         742
2         310
6         185
7         179
10        107
11         34
Name: CAP_EXC, dtype: int64
0      4365182
200      15399
97        5996
46        3372
19        2488
        ...   
60           1
93           1
69           1
79           1
38           1
Name: CODIGO_ETNIA, Length: 102, dtype: int64
2    1713511
3    1422559
6     606504
1     580767
4      62389
5      17215
Name: CODIGO_JORNADA, dtype: int64
0.0    3819031
1.0     518288
2.0      65626
Name: CARACTER,

In [ ]:
# Esta linea no corrió.. mataba el kernel de una -> omitida 
df_consolidado[cols_juan].dtypes

In [10]:
# Convertimos a category los datos que son object y parecen entrar mejor en este tipo de dato.
df_consolidado['PROVIENE_SECTOR_PRIV'] = df_consolidado['PROVIENE_SECTOR_PRIV'].astype('category')
df_consolidado['PROVIENE_OTR_MUN'] = df_consolidado['PROVIENE_OTR_MUN'].astype('category')



TIPO_DISCAPACIDAD tiene diccionario así que procedemos a insertarlo.

In [11]:
tipo_discapacidad_dict = {
    1 :  'Discapacidad auditiva - Sordera Profunda', 
    2 : 'Discapacidad auditiva - Hipoacusia o Baja audición', 
    3 : 'Discapacidad Visual - Baja visión irreversible', 
    4 :  'Discapacidad Visual - Ceguera', 
    5 :  'Discapacidad Física - Parálisis cerebral', 
    6 :  'Discapacidad Física - Lesión neuromuscular', 
    7 :  'Trastorno del espectro autista', 
    8 :  'Discapacidad intelectual - Deficiencia cognitiva',  
    9  : 'Discapacidad intelectual - Síndrome de Down', 
    10 :'Discapacidad Múltiple', 
    11 :'Otra discapacidad', 
    12 :'Discapacidad auditiva - Usuario de lengua de señas Colombiana', 
    13 :'Discapacidad auditiva usuario del castellano', 
    14 :'Sordoceguera', 
    15 :'Discapacidad física', 
    17 :'Sistémica', 
    18 :'Discapacidad Psicosocial (mental) ',
    19 :'Trastorno permanente de voz y habla ',
    99 : 'No aplica'
}
df_consolidado['TIPO_DISCAPACIDAD'] = df_consolidado['TIPO_DISCAPACIDAD'].replace(tipo_discapacidad_dict)
df_consolidado['TIPO_DISCAPACIDAD'] = df_consolidado['TIPO_DISCAPACIDAD'].astype('category')

CAP_EXC significa capacidades excepcionales. Procedemos a introducir el diccionario.


In [12]:
# curiosamente no hay 8. Tampoco en la base de datos
capacidades_excepcionales_dict = {    
    1: 'Capacidades Excepcionales',  
    2: 'Otras capacidades',                                                                                                         
    3 :'Talento excepcional en ciencias naturales o básicas',                                                                            
    4 :'Talento excepcional en artes o letras',
    5 :'Talento excepcional en actividad física, ejercicio y deporte',
    6 :'Doble excepcionalidad',          
    7 :'Talento excepcional en ciencias sociales o humanas',                     
    10 :'Talento excepcional en tecnología', 
    11 :'Talento excepcional en liderazgo social y emprendimiento',                                                                                              
    9 : 'No Aplica'  
}
df_consolidado['CAP_EXC'] = df_consolidado['CAP_EXC'].replace(capacidades_excepcionales_dict)
df_consolidado['CAP_EXC'] = df_consolidado['CAP_EXC'].astype('category')
# Cambiamos el nombre de la columna.
df_consolidado.rename(columns={'CAP_EXC': 'CAPACIDADES_EXCEPCIONALES'}, inplace=True)

CODIGO_ETNIA es la vaina más larga. Vamos a cambiar según el diccionario.

In [13]:
# estos son los indices Algunos números no aparecen, como 999, no sé si valga la pena eliminarlos.
# tampoco creo que sea  muy eficiente meter los nombres al df por ahora. Además, tienen los nombres más problemáticos.
df_consolidado['CODIGO_ETNIA'].unique()

array([  0,  46,  49, 200,  75,  97,  19, 999,  83,   1,  45,  26,   4,
        29,  74,  53,  44,  77,  12,  34,  95,  80,   9,  20,  10,  42,
        73,  72,  99,  71,  52,   7,  47, 100,  27,  17,  15,  25,   5,
        14,  31,  66,  70,  28,   2,  48, 400,  22,  18,   6,  57,  64,
         3,  65,  13, 101,  33,  32,  67,   8,  35, 998,  16,  50,  23,
        37,  56,  11,  58,  51,  85,  96,  86,  62,  40,  30,  54,  38,
        82,  90,  36,  43,  21,  61,  24,  92,  81,  55,  68,  60,  94,
       107,  69, 102,  39,  59,  79,  93,  84,  98, 109,  76])

In [14]:
#Me limito a copiar el diccionario.
Etnia_dict = {
    
    0: 'No aplica',
    1 :'Achagua',
    2 :'Amorúa' ,
    3 :'Andoque',
    4 :'Arhuaco',
    5 :'Awa',
    6 :'Bara',
    7 :'Barasano',
    8 :'Barí',
    9 :'Betoye (Guahibo)',
    10 :'Bora',
    11 :'Kawiyarí (Cabiyari)',
    12 :'Karapana (Carapana)',
    13 :'Karijona (Carijona)',
    14 :'Chimilas',
    15 :'Chiricoa',
    16 :'Cocama',
    17 :'Coconuco',
    18 :'Kofán',
    19 :'Pijaos (Coyaimas - Natagaimas)',
    20 :'Cubeo',
    21 :'Cuiva (Cuiba - Kuiba)',
    22 :'Curripaco',
    23: 'Desano',
    24 :'Tamas (Dujos de Paniquita)',
    25 :'Embera',
    26 :'Embera Katío',
    27 :'Embera Chami',
    28 :'Eperara Siapidara',
    29 :'Guambiano (autodenominación Nam Misak)',
    30 :'Guanaca',
    31 :'Guayabero (autodenominación JIW)',
    33 :'Hitnú',
    34 :'Inga',
    35 :'Camenstsa (Kamsa o Kamentsa)',
    36 :'Kogui',
    37 :'Coreguaje',
    38 :'Letuama',
    39 :'Macaguaje',
    40 :'Nukak Makú (se incluyen Humhu, Juhup, Jujupda, Kakua)',
    41 :'Makuna',
    42 :'Masiware (Masiguare - Maiben)',
    43 :'Matapí',
    44 :'Miraña',
    45 :'Muinane',
    46 :'Muisca',
    47 :'Nonuya',
    48 :'Ocaina',
    49 :'Paéz (autodenominación Nasa)',
    50 :'Pastos',
    51 :'Piapoco',
    52 :'Piaroa',
    53 :'Piratapuyo',
    54 :'Pisamira',
    55 :'Puinave',
    56 :'Sáliva (Saliba)',
    57 :'Sikuani (Sicuani)',
    58 :'Siona',
    59 :'Siriano',
    60 :'Tsiripu (Tshiripo)',
    61 :'Taiwano',
    62 :'Tanimuka',
    63 :'Tariano',
    64 :'Tatuyo',
    65 :'Tikuna',
    66 :'Totoró',
    67 :'Tukano',
    68 :'Cuna (Tule)',
    69 :'Tuyuka',
    70 :'U´wa',
    71 :'Guanano (Wanano)',
    72 :'Wayuu' ,
    73 :'Uitotos (Huitoto - Witoto)',
    74 :'Wiwa',
    75 :'Waunana (Wounaan)',
    76 :'Yagua',
    77 :'Yanacona',
    78 :'Yauna',
    79 :'Yucuna',
    80 :'Yuko (Yukpa)',
    81 :'Yurí',
    82 :'Yuruti (Tapuya)',
    83 :'Zenú (Senu)',
    84 :'Quillacingas',
    90 :'Mura',
    94 :'Polindaras',
    95 :'Raizal',
    96 :'Kankuamo',
    97 :'Afrodescendiente',
    98 :'Palanquero',
    99 :'Mokana',
    100 :'Ambalo',
    101 :'Kichwa',
    102 :'Baniva',
    103 :'Guariquema',
    104 :'Jurumi (Urtumi)',
    105 :'Kizgo (Quisgo)',
    106 :'Macahua(N)',
    107 :'Murui (Murui - Wito)',
    108 :'Wipiwi',
    109 :'Yamalero',
    110 :'Yari',
    111 :'Yaruro',
    112 :'Mapayerry',
    200 :'Negritudes',
    400 :'Rom'

}

In [15]:
# añado diccionario de CODIGO_JORNADA
codigo_jornada_dict = {
    1:  'Completa',
    2 : 'Mañana',
    3 : 'Tarde',
    4 : 'Nocturna',                                                                                                                                            
    5 : 'Fin de semana',
    6 : 'Única'   
}
df_consolidado['CODIGO_JORNADA'] = df_consolidado['CODIGO_JORNADA'].replace(codigo_jornada_dict)
df_consolidado['CODIGO_JORNADA'] = df_consolidado['CODIGO_JORNADA'].astype('category') 
# Para ver si tiene problemas con la ñ
print(df_consolidado['CODIGO_JORNADA'].unique())

['Única', 'Tarde', 'Mañana', 'Nocturna', 'Completa', 'Fin de semana']
Categories (6, object): ['Única', 'Tarde', 'Mañana', 'Nocturna', 'Completa', 'Fin de semana']


In [16]:
df_consolidado['CARACTER'] = df_consolidado['CARACTER'].astype('int64')
print(df_consolidado['CARACTER'].unique())

[1 0 2]


In [17]:
# añado diccionario de CARACTER

caracter_dict = {    
    0 : 'No aplica',
    1 : 'Academico',
    2 : 'Tecnico'
}
df_consolidado['CARACTER'] = df_consolidado['CARACTER'].replace(caracter_dict)
df_consolidado['CARACTER'] = df_consolidado['CARACTER'].astype('category')


Ahora bien, CÓDIGO ESPECIALIDAD presenta los mismos datos del diccionario, así que vamos a traducirlos.



In [18]:
# convertimos CODIGO_ESPECIALIDAD de acuerdo al diccionario. Del tipo 16 no hay ni un solo dato. 
codigo_especialidad_dict = {
    0 : 'No aplica',
    5 : 'Academico',
    6 : 'Industrial',
    7 : 'Otro',
    8 : 'Comercial',
    9 : 'Pedagogico',                                                                                                         
    10: 'Agropecuario',
    16: 'Promocion social'
}
df_consolidado['CODIGO_ESPECIALIDAD'] = df_consolidado['CODIGO_ESPECIALIDAD'].replace(codigo_especialidad_dict)
df_consolidado['CODIGO_ESPECIALIDAD'] = df_consolidado['CODIGO_ESPECIALIDAD'].astype('category')



Resultado

In [19]:
cols_juan = [item.replace( 'CAP_EXC', 'CAPACIDADES_EXCEPCIONALES') for item in cols_juan]
cols_juan

['PROVIENE_SECTOR_PRIV',
 'PROVIENE_OTR_MUN',
 'TIPO_DISCAPACIDAD',
 'CAPACIDADES_EXCEPCIONALES',
 'CODIGO_ETNIA',
 'CODIGO_JORNADA',
 'CARACTER',
 'CODIGO_ESPECIALIDAD',
 'CODIGO_GRADO']

In [ ]:
df_consolidado[cols_juan].dtypes

## Parte III: Lici

cols_lici = ['CODIGO_METODOLOGIA', 'SIT_ACAD_ANIO_ANT', 'CON_ALUM_ANIO_ANT', 'ZONA_RESI_ALU', 'CODIGO_INTERNADO', 'EDAD', 'NIVEL', 'DIR_NUM_LOCALIDAD', 'DIR_LOCALIDAD']

In [20]:
#numero de localidad: todos los numeros se pasan a str.
df_consolidado['DIR_NUM_LOCALIDAD'] = df_consolidado['DIR_NUM_LOCALIDAD'].astype(str).str.strip().str.replace(",.*","", regex = True)
#se crea diccionario de números y nombres de localidad:
localidadesdicc = {'1' : 'Usaquén', '2' : 'Chapinero',
                   '3' : 'Santa Fe', '4' : 'San Cristóbal', '5' : 'Usme', '6' : 'Tunjuelito', '7' : 'Bosa', '8' : 'Kennedy', '9' : 'Fontibón', '10' : 'Engativá', '11' : 'Suba', '12' : 'Barrios Unidos', '13' : 'Teusaquillo', '14' : 'Los Mártires', '15' : 'Antonio Nariño', '16' : 'Puente Aranda', '17' : 'La Candelaria', '18' : 'Rafael Uribe Uribe', '19' : 'Ciudad Bolívar', '20' : 'Sumapaz'}

In [21]:
#se reemplaza el diccionario en la var DIR_LOCALIDAD:
df_consolidado['DIR_LOCALIDAD'] = df_consolidado['DIR_NUM_LOCALIDAD'].replace(localidadesdicc)

In [ ]:
#COLUMNA EDAD 

## Parte IV: Pablo

cols_pablo = ['RES_DEPTO', 'RES_MUN', 'ESTRATO', 'SISBEN', 'FECHA_NACIMIENTO', 'GENERO', 'POB_VICT_CONF', 'DPTO_EXP', 'MUN_EXP'] 

In [22]:
#  RES_DEPTO y RES_DEPTO
df_consolidado["RES_DEPTO"] = df_consolidado["RES_DEPTO"].astype('category')
df_consolidado["RES_MUN"] = df_consolidado["RES_MUN"].astype('category')

**Observation**:We transform the colummns to object type

In [ ]:
# .astype('category')
df_consolidado["ESTRATO"].value_counts()

**Observation**: 9897 observations have 9 as Estrato. This is erroneous, so we will replace it with NAN. The we will transform the variable to object category

In [23]:
df_consolidado["ESTRATO"] = df_consolidado["ESTRATO"].replace(9, None)
df_consolidado["ESTRATO"] = df_consolidado["ESTRATO"].astype('category')

In [ ]:
crosstab = pd.crosstab(df_consolidado["ANO_INF"], df_consolidado["ESTRATO"], normalize = "index")*100
ax = crosstab.plot(kind='bar', stacked=True, figsize=(10, 6))
ax.set_ylabel('%')
ax.set_ylabel('Year')
ax.set_title("Estrato (%) each year")
plt.legend(title='ESTRATO', bbox_to_anchor=(1.0, 1), loc='upper left')
plt.show()

In [24]:
# SISBEN
df_consolidado["SISBEN"] = df_consolidado["SISBEN"].str.replace(",",".").str.replace(" ", "")
df_consolidado["SISBEN"] = pd.to_numeric(df_consolidado["SISBEN"], errors='coerce')

In [25]:
df_consolidado["SISBEN"][df_consolidado["ANO_INF"] == 2017].value_counts()

0.01     151006
0.00      15205
1.00       3743
9.00       2894
61.20      1262
          ...  
8.20          1
2.61          1
70.21         1
68.83         1
10.04         1
Name: SISBEN, Length: 7376, dtype: int64

In [26]:
df_consolidado["SISBEN"][df_consolidado["ANO_INF"] == 2021].value_counts()

0.00     478433
0.01      54514
1.00      26274
9.00       3201
2.00       2721
          ...  
17.56         1
0.69          1
13.70         1
1.15          1
86.88         1
Name: SISBEN, Length: 7129, dtype: int64

**Observation**: It seems that the coding of "0" was done differently in 2021. While in the other years few students have a score of 0, in 2021 almost half have this score.

**Solution**: Since in 2021 it is not possible to differentiate between an original "0" and a "0" placed as a replacement for empty values, we will just ignore the "0" in all the variables


In [27]:
df_consolidado["SISBEN"][df_consolidado["SISBEN"] == 0] = np.nan  

<ipython-input-27-3493a5859704>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_consolidado["SISBEN"][df_consolidado["SISBEN"] == 0] = np.nan


In [ ]:
Sis2017 = df_consolidado["SISBEN"][df_consolidado["ANO_INF"] == 2017]
Sis2018 = df_consolidado["SISBEN"][df_consolidado["ANO_INF"] == 2018]
Sis2019 = df_consolidado["SISBEN"][df_consolidado["ANO_INF"] == 2019]
Sis2020 = df_consolidado["SISBEN"][df_consolidado["ANO_INF"] == 2020]
Sis2021 = df_consolidado["SISBEN"][df_consolidado["ANO_INF"] == 2021]

sns.set(style="darkgrid")

fig, axs = plt.subplots(2, 3, figsize=(22, 15))

sns.histplot(data=Sis2017, x=Sis2017, kde=True, color="skyblue", ax=axs[0, 0])
sns.histplot(data=Sis2018, x=Sis2018, kde=True, color="olive", ax=axs[0, 1])
sns.histplot(data=Sis2019, x=Sis2019, kde=True, color="gold", ax=axs[0, 2])
sns.histplot(data=Sis2020, x=Sis2020, kde=True, color="teal", ax=axs[1, 0])
sns.histplot(data=Sis2021, x=Sis2021, kde=True, color="teal", ax=axs[1, 1])

axs[0, 0].set_title('2017')
axs[0, 1].set_title('2018')
axs[0, 2].set_title('2019')
axs[1, 0].set_title('2020')
axs[1, 1].set_title('2021')


plt.show()

In [28]:
# FECHA_NACIMIENTO'
df_consolidado["FECHA_NACIMIENTO"] = pd.to_datetime(df_consolidado["FECHA_NACIMIENTO"])

In [29]:
# GENERO
df_consolidado["GENERO"] = df_consolidado["GENERO"].astype('category')


In [30]:
# POB_VICT_CONF
# convertimos POB_VICT_CONF de acuerdo al diccionario. Del tipo 16 no hay ni un solo dato. 
POB_VICT_CONF_DICT = {
    1 : "En situación de desplazamiento",
    2 : "Desvinculados de grupos armados",
    3 : "Hijos de adultos desmovilizados",
    4 : "Victimas de minas",
    5 : "Responsabilidad penal",
    6 : "Acto terrorista /Atentados/ Combates/ Enfrentamientos / Hostigamientos",
    7 : "Amenaza",
    8 : "Delitos contra la libertad e integridad sexual en el marco del conflicto armado",
    9 : "Desaparicion Forzada",
    10 : "Desplazamiento Forzado",
    11 : "Homicidio",
    12 : "Secuestro",
    13 : "Tortura",
    14 : "Vinculacion de niños niñas adolescentes a Actividades relacionadas con grupos armados",
    15 : "Abandono o despojo de tierras",
    16 : "Perdida de bienes muebles o inmuebles" ,
    17 : "Otros",
    18 : "Sin información",
    19 : "Confinamiento",
    20 : "Lesiones personales físicas",
    21 : "Lesiones personales Psicológicas",
    99 : "No aplica",
}
df_consolidado['POB_VICT_CONF'] = df_consolidado['POB_VICT_CONF'].replace(POB_VICT_CONF_DICT)
df_consolidado['POB_VICT_CONF'] = df_consolidado['POB_VICT_CONF'].astype('category')


**Observation**: We transform the variable POB_VICT_CONF according to its dictionary.


In [31]:
# DPTO_EXP and MUN_EXP
df_consolidado['DPTO_EXP'] = df_consolidado['DPTO_EXP'].astype('category')
df_consolidado['MUN_EXP'] = df_consolidado['MUN_EXP'].astype('category')


**Observation**:We transform the colummns to object type

### Final
Faltaría tratar por separado la limpieza de Repitente, ya que a nadie le correspondió esta columna. Es mejor dejarla category? Hacemos verificación de que sea coherente comparando año a año NRO_documentos?

# Descomentar y ejecutar para generar el dataset final

In [32]:
df_consolidado.to_csv('data/2-plata/Consolidado_SIMAT_Depurado.csv')