# Limpieza de datos

Cargamos la base

In [1]:
# Scientific libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
# Pandas options
pd.options.display.max_columns = None

In [2]:
# first option to read the dataset
df_consolidado = pd.read_csv('data/1-bronce/Consolidado-SIMAT-2017-2021.csv', index_col=0)

/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (5,33,36,39,40) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/opt/conda/lib/python3.8/site-packages/numpy/lib/arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [3]:
df_consolidado.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4402945 entries, 0 to 4464570
Data columns (total 40 columns):
 #   Column                Dtype  
---  ------                -----  
 0   ANO_INF               int64  
 1   CODIGO_DANE           int64  
 2   CODIGO_DANE_SEDE      int64  
 3   TIPO_DOCUMENTO        int64  
 4   NRO_DOCUMENTO         object 
 5   APELLIDO1             object 
 6   APELLIDO2             object 
 7   NOMBRE1               object 
 8   NOMBRE2               object 
 9   DIRECCION_RESIDENCIA  object 
 10  RES_DEPTO             int64  
 11  RES_MUN               int64  
 12  ESTRATO               int64  
 13  SISBEN                object 
 14  FECHA_NACIMIENTO      object 
 15  GENERO                object 
 16  POB_VICT_CONF         int64  
 17  DPTO_EXP              object 
 18  MUN_EXP               object 
 19  PROVIENE_SECTOR_PRIV  object 
 20  PROVIENE_OTR_MUN      object 
 21  TIPO_DISCAPACIDAD     int64  
 22  CAP_EXC               int64  
 23  CODIGO_

In [4]:
# Convierte a String NRO_DOCUMENTO Y Direccion
df_consolidado['NRO_DOCUMENTO'] = df_consolidado['NRO_DOCUMENTO'].astype(str)
df_consolidado['DIRECCION_RESIDENCIA'] = df_consolidado['DIRECCION_RESIDENCIA'].astype(str)
# Elimina info de nombres
df_consolidado.drop(['APELLIDO1', 'APELLIDO2', 'NOMBRE1', 'NOMBRE2', 'VALORACION1', 'VALORACION2'], inplace=True, axis=1)

In [5]:
df_consolidado['NRO_DOCUMENTO'].str.contains('\D', regex=True).value_counts()

False    4321467
True       81478
Name: NRO_DOCUMENTO, dtype: int64

In [6]:
((df_consolidado['NRO_DOCUMENTO'].str.contains('\D', regex=True)) & (df_consolidado['TIPO_DOCUMENTO'].isin([1,2,3]))).value_counts()

False    4400079
True        2866
dtype: int64

In [7]:
# df_consolidado["RES_DEPTO"] = df_consolidado["RES_DEPTO"].astype('category')
df_consolidado["RES_DEPTO"].unique()

array([11, 85, 50, 73, 25, 15, 23, 54, 41, 47, 27,  5,  8, 13, 17, 19, 76,
       44, 66, 70, 68, 20, 63, 52, 81, 95, 99, 86, 18, 88, 94, 91, 97])

In [8]:
df_consolidado["RES_MUN"].unique()

array([  1, 606, 313, 718, 675, 286, 176, 239, 443, 754, 520, 568, 306,
       148, 269, 430, 250, 483, 168, 634, 140, 238,  13, 660, 290, 275,
       740, 132, 821, 834, 573,   6, 380, 400, 352, 152, 555,  51, 469,
       394, 885,  45, 370, 670, 755, 574, 750, 570, 665, 175, 524, 551,
       288, 130,  81, 895, 124, 671, 455, 590, 835,  35, 396, 839, 319,
       307,  47, 322, 183, 386, 377,  88, 295, 154, 758,  30, 300, 178,
       444, 170, 299, 480,  68,  32, 530, 426, 899, 770, 777, 807, 682,
       405, 547, 517,  43, 624, 162, 318, 442, 126, 473, 212, 147, 276,
       892,  53, 875,  77, 498, 759, 592,  22, 842, 717, 245, 408, 591,
        79, 298, 433, 761, 638, 854, 810, 104, 440, 673, 367, 664, 417,
       490, 466, 545, 449, 535, 513, 843, 793, 873, 692, 668, 359, 710,
       861, 708, 215, 504, 678,  25, 397, 518, 418, 980, 182, 815, 540,
       139, 862, 658, 190, 897, 646, 703, 542, 137, 189, 667, 226, 806,
       572,  60, 787, 488, 268, 817, 650, 874, 736, 222, 836, 37

In [9]:
df_consolidado["RES_MUN"].max()

980

In [10]:
# df_consolidado["ESTRATO"] = df_consolidado["ESTRATO"].replace(9, None)
df_consolidado = df_consolidado[df_consolidado["ESTRATO"] != 9]
df_consolidado["ESTRATO"].unique()


array([2, 3, 0, 1, 4, 6, 5])

In [11]:
df_consolidado["SISBEN"] = df_consolidado["SISBEN"].str.replace(",",".").str.replace(" ", "")
df_consolidado["SISBEN"] = pd.to_numeric(df_consolidado["SISBEN"], errors='coerce')

In [12]:
df_consolidado["SISBEN"].dtype

dtype('float64')

In [13]:
df_consolidado["SISBEN"].min()

0.0

In [14]:
df_consolidado["FECHA_NACIMIENTO"] = pd.to_datetime(df_consolidado["FECHA_NACIMIENTO"])

In [15]:
# df_consolidado.drop(['FECHA_NACIMIENTO'], inplace=True, axis=1)

In [16]:
df_consolidado["GENERO"].unique()

array(['F', 'M'], dtype=object)

In [17]:
len('M'.encode('utf-8'))

1

In [18]:
df_consolidado['POB_VICT_CONF'].unique()

array([ 9,  1,  2,  3,  4,  5, 99, 10, 18,  6, 17,  7, 14, 20, 15, 16, 12,
       19,  8, 11, 21, 13])

In [19]:
(df_consolidado['DPTO_EXP'] == ' ').value_counts()

True     4262055
False     130993
Name: DPTO_EXP, dtype: int64

In [20]:
df_consolidado['DPTO_EXP'] = df_consolidado['DPTO_EXP'].str.strip().replace('^0+', '', regex = True)
df_consolidado['DPTO_EXP'] = df_consolidado['DPTO_EXP'].replace('', ' ')
df_consolidado['DPTO_EXP'].unique()

array([' ', '73', '25', '95', '76', '20', '50', '18', '15', '54', '68',
       '5', '23', '13', '41', '11', '17', '47', '52', '85', '86', '27',
       '8', '81', '19', '63', '70', '44', '99', '66', '97', '91', '94',
       '88'], dtype=object)

In [21]:
(df_consolidado['MUN_EXP'] == ' ').value_counts()

True     4262055
False     130993
Name: MUN_EXP, dtype: int64

In [22]:
df_consolidado['MUN_EXP'] = df_consolidado['MUN_EXP'].str.strip().replace('^0+', '', regex = True)
# df_consolidado = df_consolidado[df_consolidado['MUN_EXP'] != '']
df_consolidado['MUN_EXP'] = df_consolidado['MUN_EXP'].replace('', ' ')
df_consolidado['MUN_EXP'].unique()

array([' ', '616', '867', '394', '1', '148', '878', '555', '497', '596',
       '111', '228', '885', '590', '860', '686', '168', '236', '689',
       '81', '24', '120', '460', '606', '483', '837', '839', '675', '711',
       '670', '873', '6', '29', '51', '251', '319', '349', '411', '744',
       '268', '660', '25', '109', '250', '622', '810', '245', '290',
       '132', '676', '592', '298', '835', '217', '136', '55', '189',
       '200', '408', '183', '141', '507', '897', '79', '20', '288', '65',
       '101', '233', '410', '68', '244', '43', '807', '701', '320', '283',
       '753', '325', '130', '417', '823', '35', '97', '777', '773', '787',
       '30', '662', '350', '899', '359', '708', '785', '206', '438',
       '698', '26', '137', '147', '124', '688', '110', '600', '272', '90',
       '862', '406', '568', '313', '551', '495', '654', '347', '377',
       '834', '572', '571', '758', '573', '212', '683', '580', '381',
       '368', '754', '678', '380', '361', '892', '865', '67', '

In [23]:
df_consolidado.drop(['DPTO_EXP', 'MUN_EXP'], inplace=True, axis=1)

In [24]:
# df_consolidado['PROVIENE_SECTOR_PRIV'] = df_consolidado['PROVIENE_SECTOR_PRIV']
df_consolidado['PROVIENE_SECTOR_PRIV'].unique()

array(['N', 'S'], dtype=object)

In [25]:
# df_consolidado['PROVIENE_OTR_MUN'] = df_consolidado['PROVIENE_OTR_MUN'].astype('category')
df_consolidado['PROVIENE_OTR_MUN'].unique()

array(['N', 'S'], dtype=object)

In [26]:
df_consolidado['TIPO_DISCAPACIDAD'].unique()

array([99,  7,  8, 10, 18, 15, 13, 11,  3,  4, 19, 17, 14,  6, 12,  1,  2,
        9,  5, 16])

In [27]:
df_consolidado['CAP_EXC'].unique()

array([ 9,  4,  1,  3,  2,  5,  6,  7, 11, 10])

In [28]:
df_consolidado['CODIGO_ETNIA'].unique()

array([  0,  46,  49, 200,  75,  97,  19, 999,  83,   1,  45,  26,   4,
        29,  74,  53,  44,  77,  12,  34,  95,  80,   9,  20,  10,  42,
        73,  72,  99,  71,  52,   7,  47, 100,  27,  17,  15,  25,   5,
        14,  31,  66,  70,  28,   2,  48, 400,  22,  18,   6,  57,  64,
         3,  65,  13, 101,  33,  32,  67,   8,  35, 998,  16,  50,  23,
        37,  56,  11,  58,  51,  85,  96,  86,  62,  40,  30,  54,  38,
        82,  90,  36,  43,  21,  61,  24,  92,  81,  55,  68,  60,  94,
       107,  69, 102,  39,  59,  79,  93,  84,  98, 109,  76])

In [29]:
df_consolidado['CODIGO_JORNADA'].unique()

array([6, 3, 2, 4, 1, 5])

In [30]:
df_consolidado['CARACTER'] = df_consolidado['CARACTER'].astype(int)
df_consolidado['CARACTER'].unique()

array([1, 0, 2])

In [31]:
df_consolidado['CODIGO_ESPECIALIDAD'].unique()

array([ 5,  0,  6,  8,  9,  7, 10])

In [32]:
df_consolidado['CODIGO_GRADO'].unique()

array([10,  0,  3, -1,  9,  7, 11,  8,  6,  5,  2,  4,  1, 99, 25, 26, 23,
       24, 22, -2, 21, 12, 13])

In [33]:
df_consolidado['CODIGO_METODOLOGIA'].unique()

array([ 1,  9, 10, 20, 11,  2, 12])

In [34]:
df_consolidado['REPITENTE'].unique()

array(['N', 'S'], dtype=object)

In [35]:
df_consolidado['SIT_ACAD_ANIO_ANT'].unique()

array([1, 0, 8, 2])

In [36]:
df_consolidado['CON_ALUM_ANIO_ANT'] = df_consolidado['CON_ALUM_ANIO_ANT'].astype(int)
df_consolidado['CON_ALUM_ANIO_ANT'].unique()

array([9, 8, 5, 3])

In [37]:
df_consolidado['ZONA_RESI_ALU'] = df_consolidado['ZONA_RESI_ALU'].astype(str)
df_consolidado['ZONA_RESI_ALU'].unique()

array(['1', '2', ' '], dtype=object)

In [38]:
(df_consolidado['ZONA_RESI_ALU'] == ' ').value_counts()

False    4393047
True           1
Name: ZONA_RESI_ALU, dtype: int64

In [39]:
df_consolidado = df_consolidado[df_consolidado['ZONA_RESI_ALU'] != ' ']
df_consolidado['ZONA_RESI_ALU'] = df_consolidado['ZONA_RESI_ALU'].astype(int)
df_consolidado['ZONA_RESI_ALU'].unique()

array([1, 2])

In [40]:
df_consolidado['CODIGO_INTERNADO'] = df_consolidado['CODIGO_INTERNADO'].astype(str)
df_consolidado['CODIGO_INTERNADO'] = df_consolidado['CODIGO_INTERNADO'].replace(' ', '3').astype(int)
df_consolidado['CODIGO_INTERNADO'].unique()

array([3])

In [41]:
df_consolidado.drop(['CODIGO_INTERNADO'], inplace=True, axis=1)

In [42]:
df_consolidado['EDAD'].sort_values().unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  91,  92,
        93,  97, 100])

In [43]:
df_consolidado['NIVEL'].unique()

array([4, 1, 2, 3, 7])

In [44]:
(df_consolidado['NIVEL'] == 7).value_counts()

False    4393046
True           1
Name: NIVEL, dtype: int64

In [45]:
df_consolidado = df_consolidado[df_consolidado['NIVEL'] != 7]

In [46]:
df_consolidado['DIR_NUM_LOCALIDAD'].unique()

array([16, 8, 1, 10, 4, 12, 11, 13, 7, 6, 3, 18, 15, 17, 5, 14, 9, 19, 2,
       20, '16', '18', '19', '11', '8', '9', '10', '2', '   16,00',
       '    8,00', '    1,00', '    4,00', '   10,00', '   12,00',
       '   11,00', '   13,00', '    7,00', '    5,00', '    6,00',
       '    3,00', '   18,00', '   15,00', '   17,00', '   19,00',
       '   14,00', '    9,00', '    2,00', '   20,00', ' ', '20'],
      dtype=object)

In [47]:
(df_consolidado['DIR_NUM_LOCALIDAD'] == " ").value_counts()

False    4393031
True          15
Name: DIR_NUM_LOCALIDAD, dtype: int64

In [48]:
df_consolidado = df_consolidado[df_consolidado['DIR_NUM_LOCALIDAD'] != " "]

In [49]:
df_consolidado['DIR_NUM_LOCALIDAD'] = df_consolidado['DIR_NUM_LOCALIDAD'].astype(str).str.strip().str.replace(",.*","", regex = True)
df_consolidado['DIR_NUM_LOCALIDAD'] = df_consolidado['DIR_NUM_LOCALIDAD'].astype(int)
df_consolidado['DIR_NUM_LOCALIDAD'].unique()

array([16,  8,  1, 10,  4, 12, 11, 13,  7,  6,  3, 18, 15, 17,  5, 14,  9,
       19,  2, 20])

In [50]:
df_consolidado.drop(['DIR_LOCALIDAD'], inplace=True, axis=1)

In [51]:
# df_consolidado

In [52]:
# df_consolidado.info()

In [53]:
# df_consolidado.columns.tolist()

In [54]:
# df_consolidado.to_csv('data/2-plata/Consolidado_SIMAT_Depurado.csv')

In [57]:
# df_consolidado = pd.read_csv('data/2-plata/Consolidado_SIMAT_Depurado.csv',
#                              index_col=0,
#                              dtype={
#                                  'ANO_INF':              'uint16',
#                                  'CODIGO_DANE':          'uint64',
#                                  'CODIGO_DANE_SEDE':     'uint64',
#                                  'TIPO_DOCUMENTO':       'uint8',
#                                  'NRO_DOCUMENTO':        'string',
#                                  'DIRECCION_RESIDENCIA': 'string',
#                                  'RES_DEPTO':            'uint8',
#                                  'RES_MUN':              'uint16',
#                                  'ESTRATO':              'uint8',
#                                  'SISBEN':               'float16',
#                                  'GENERO':               'string',
#                                  'POB_VICT_CONF':        'uint8',
#                                  'PROVIENE_SECTOR_PRIV': 'string',
#                                  'PROVIENE_OTR_MUN':     'string',
#                                  'TIPO_DISCAPACIDAD':    'uint8',
#                                  'CAP_EXC':              'uint8',
#                                  'CODIGO_ETNIA':         'uint16',
#                                  'CODIGO_JORNADA':       'uint8',
#                                  'CARACTER':             'uint8',
#                                  'CODIGO_ESPECIALIDAD':  'uint8',
#                                  'CODIGO_GRADO':         'int8',
#                                  'CODIGO_METODOLOGIA':   'uint8',
#                                  'REPITENTE':            'string',
#                                  'SIT_ACAD_ANIO_ANT':    'uint8',
#                                  'CON_ALUM_ANIO_ANT':    'uint8',
#                                  'ZONA_RESI_ALU':        'uint8',
#                                  'EDAD':                 'uint8',
#                                  'NIVEL':                'uint8',
#                                  'DIR_NUM_LOCALIDAD':    'uint8'
#                              },
#                              # Descomentar la linea de abajo si quieren que se convierta
#                              # la variable 'FECHA_NACIMIENTO' a datetime
#                              # parse_dates=True
#                             )

In [58]:
# df_consolidado.head()

In [59]:
# df_consolidado.info(show_counts=True)

In [60]:
def calcular_nivel_sisben(row):
    puntaje = row['SISBEN']
    zona = int(row['ZONA_RESI_ALU'])
    if math.isnan(puntaje):
        return 0
    elif ((0.00 <= puntaje <= 44.79) and  zona == 1) or ((0.00 <= puntaje <= 32.98) and zona == 2):
        return 1
    elif ((44.80 <= puntaje <= 51.57) and  zona == 1) or ((32.99 <= puntaje <= 37.80) and zona == 2):
        return 2
    elif (puntaje > 51.57 and  zona == 1) or (puntaje > 37.80 and zona == 2):
        return 3
    else:
        return np.nan
df_consolidado['NIVEL_SISBEN'] = df_consolidado[['SISBEN', 'ZONA_RESI_ALU']].apply(calcular_nivel_sisben, axis=1)
df_consolidado

ANO_INF   CODIGO_DANE  CODIGO_DANE_SEDE  TIPO_DOCUMENTO  \
0           2017  111001000078      111001000078               2   
1           2017  111001000078      111001014834               3   
2           2017  111001000078      111001014834               3   
3           2017  111001000078      111001014834               3   
4           2017  111001000078      111001014834               3   
...          ...           ...               ...             ...   
4464566     2021  411102000293      411102000293               2   
4464567     2021  411102000293      411102000293               2   
4464568     2021  411102000293      411102000293               2   
4464569     2021  411102000293      411102000293               2   
4464570     2021  411102000293      411102000293               2   

        NRO_DOCUMENTO   DIRECCION_RESIDENCIA  RES_DEPTO  RES_MUN  ESTRATO  \
0         00010803853       CL 69 A 105 F 67         11        1        2   
1            05057637      CL 34 SUR 40 A 51         11        1        3   
2           067289989      KR 54 SUR 50 B 10         11        1        3   
3           071759788      KR 40 28 A 02 SUR         11        1        3   
4           089980482      KR 40 28 A 02 SUR         11        1        3   
...               ...                    ...        ...      ...      ...   
4464566    1012336508     KR 105 B 65 81 SUR         11        1        2   
4464567    1016713910      KR 99 A 71 39 SUR         11        1        2   
4464568    1011090034      CL 62 SUR 93 C 53         11        1        2   
4464569    1011092068    CL 61 B SUR 81 D 03         11        1        2   
4464570    1029140201  CR 82 A # 61 SUR - 30         11        1        2   

         SISBEN FECHA_NACIMIENTO GENERO  POB_VICT_CONF PROVIENE_SECTOR_PRIV  \
0          0.01       2000-01-08      F              9                    N   
1           NaN       2012-06-13      F              9                    N   
2           NaN       2008-10-07      M              9                    N   
3           NaN       2012-08-23      M              9                    N   
4           NaN       2013-11-16      F              9                    N   
...         ...              ...    ...            ...                  ...   
4464566   54.68       2005-09-06      F             99                    N   
4464567   61.21       2005-10-01      F             99                    N   
4464568   58.21       2005-11-30      F             99                    N   
4464569   58.24       2006-02-24      F             99                    N   
4464570   57.18       2005-01-13      F             99                    N   

        PROVIENE_OTR_MUN  TIPO_DISCAPACIDAD  CAP_EXC  CODIGO_ETNIA  \
0                      N                 99        9             0   
1                      N                 99        9             0   
2                      N                  7        9             0   
3                      N                 99        9             0   
4                      N                 99        9             0   
...                  ...                ...      ...           ...   
4464566                N                 99        9             0   
4464567                N                 99        9             0   
4464568                N                 99        9             0   
4464569                N                 99        9             0   
4464570                N                 99        9             0   

         CODIGO_JORNADA  CARACTER  CODIGO_ESPECIALIDAD  CODIGO_GRADO  \
0                     6         1                    5            10   
1                     3         0                    0             0   
2                     3         0                    0             3   
3                     3         0                    0             0   
4                     3         0                    0            -1   
...                 ...       ...            

In [61]:
df_consolidado['NIVEL_SISBEN'].isnull().value_counts()

False    4393031
Name: NIVEL_SISBEN, dtype: int64

In [62]:
df_consolidado['NIVEL_SISBEN'] = df_consolidado['NIVEL_SISBEN'].astype('uint8')

In [63]:
# df_consolidado.to_csv('data/2-plata/Consolidado_SIMAT_Depurado.csv')

In [64]:
# df_consolidado = pd.read_csv('data/2-plata/Consolidado_SIMAT_Depurado.csv',
#                              index_col=0,
#                              dtype={
#                                  'ANO_INF':              'uint16',
#                                  'CODIGO_DANE':          'uint64',
#                                  'CODIGO_DANE_SEDE':     'uint64',
#                                  'TIPO_DOCUMENTO':       'uint8',
#                                  'NRO_DOCUMENTO':        'string',
#                                  'DIRECCION_RESIDENCIA': 'string',
#                                  'RES_DEPTO':            'uint8',
#                                  'RES_MUN':              'uint16',
#                                  'ESTRATO':              'uint8',
#                                  'SISBEN':               'float16',
#                                  'GENERO':               'string',
#                                  'POB_VICT_CONF':        'uint8',
#                                  'PROVIENE_SECTOR_PRIV': 'string',
#                                  'PROVIENE_OTR_MUN':     'string',
#                                  'TIPO_DISCAPACIDAD':    'uint8',
#                                  'CAP_EXC':              'uint8',
#                                  'CODIGO_ETNIA':         'uint16',
#                                  'CODIGO_JORNADA':       'uint8',
#                                  'CARACTER':             'uint8',
#                                  'CODIGO_ESPECIALIDAD':  'uint8',
#                                  'CODIGO_GRADO':         'int8',
#                                  'CODIGO_METODOLOGIA':   'uint8',
#                                  'REPITENTE':            'string',
#                                  'SIT_ACAD_ANIO_ANT':    'uint8',
#                                  'CON_ALUM_ANIO_ANT':    'uint8',
#                                  'ZONA_RESI_ALU':        'uint8',
#                                  'EDAD':                 'uint8',
#                                  'NIVEL':                'uint8',
#                                  'DIR_NUM_LOCALIDAD':    'uint8',
#                                  'NIVEL_SISBEN':         'uint8'
#                              },
#                              # Descomentar la linea de abajo si quieren que se convierta
#                              # la variable 'FECHA_NACIMIENTO' a datetime
#                              # parse_dates=True
#                             )

In [65]:
# df_consolidado

In [66]:
df_consolidado['REPITENTE'] = df_consolidado['REPITENTE'].replace({'S': 1, 'N': 0}).astype('uint8')
df_consolidado['REPITENTE'].unique()

array([0, 1], dtype=uint8)

In [67]:
dict_etnia_recod = {
    0 : 0 ,
    200 : 2 ,
    1 : 1 ,
    97 : 5 ,
    83 : 1 ,
    46 : 1 ,
    19 : 1 ,
    8 : 1 ,
    96 : 1 ,
    95 : 4 ,
    73 : 1 ,
    75 : 1 ,
    6 : 1 ,
    101 : 1 ,
    45 : 1 ,
    49 : 1 ,
    72 : 1 ,
    35 : 1 ,
    107 : 1 ,
    65 : 1 ,
    27 : 1 ,
    74 : 1 ,
    50 : 1 ,
    98 : 6 ,
    5 : 1 ,
    66 : 1 ,
    12 : 1 ,
    31 : 1 ,
    26 : 1 ,
    48 : 1 ,
    4 : 1 ,
    16 : 1 ,
    22 : 1 ,
    34 : 1 ,
    29 : 1 ,
    2 : 1 ,
    18 : 1 ,
    7 : 1 ,
    47 : 1 ,
    52 : 1 ,
    17 : 1 ,
    80 : 1 ,
    15 : 1 ,
    109 : 1 ,
    53 : 1 ,
    400 : 3 ,
    77 : 1 ,
    25 : 1 ,
    28 : 1 ,
    70 : 1 ,
    100 : 1 ,
    3 : 1 ,
    10 : 1 ,
    13 : 1 ,
    40 : 1 ,
    59 : 1 ,
    14 : 1 ,
    20 : 1 ,
    9 : 1 ,
    64 : 1 ,
    102 : 1 ,
    44 : 1 ,
    55 : 1 ,
    81 : 1 ,
    67 : 1 ,
    57 : 1 ,
    23 : 1 ,
    37 : 1 ,
    36 : 1 ,
    99 : 1 ,
    21 : 1 ,
    84 : 1 ,
    56 : 1 ,
    51 : 1 ,
    76 : 1 ,
    43 : 1 ,
    39 : 1 ,
    54 : 1 ,
    58 : 1 ,
    68 : 1 ,
    82 : 1 ,
    42 : 1 ,
    33 : 1 ,
    11 : 1 ,
    71 : 1,
    998: 0,
    999: 0,
    24: 1,
    30: 1,
    32: 1,
    38: 1,
    60: 1,
    61: 1,
    62: 1,
    69: 1,
    79: 1,
    85: 1,
    86: 1,
    90: 1,
    92: 1,
    93: 1,
    94: 1
}

In [68]:
df_consolidado['CODIGO_ETNIA'] = df_consolidado['CODIGO_ETNIA'].replace(dict_etnia_recod)
df_consolidado['CODIGO_ETNIA'].unique()

array([0, 1, 2, 5, 4, 3, 6])

In [69]:
def grado_overage(x):
    if x['CODIGO_GRADO'] < 0 and x['EDAD'] >= 6:
        ovage = 0
    elif x['CODIGO_GRADO'] == -1 and x['EDAD'] <= 5:
        ovage = 100
    elif x['CODIGO_GRADO'] == -2 and x['EDAD'] >= 5:
        ovage = 0        
    elif x['CODIGO_GRADO'] == -2 and x['EDAD'] <= 4:
        ovage = 100    
    elif x['EDAD']-6 <= x['CODIGO_GRADO'] and x['CODIGO_GRADO'] >= 0:
        ovage = 100
    else:
        ovage = int(100*(x['CODIGO_GRADO']) /(x['EDAD']-6))
        
    return ovage

In [70]:
df_consolidado['GRADO_OVERAGE'] = df_consolidado[['EDAD','CODIGO_GRADO']].apply(grado_overage, axis = 1 )
df_consolidado['GRADO_OVERAGE']

0           90
1          100
2          100
3          100
4          100
          ... 
4464566    100
4464567    100
4464568    100
4464569    100
4464570    100
Name: GRADO_OVERAGE, Length: 4393031, dtype: int64

In [71]:
def overage(x):        
    return 1 if x['GRADO_OVERAGE'] < 100 else 0;

In [72]:
df_consolidado['OVERAGE'] = df_consolidado[['GRADO_OVERAGE']].apply(overage, axis=1)

In [73]:
dict_discapacidad = {
15 : 1 ,
8 : 1 ,
18 : 1 ,
13 : 1 ,
7 : 1 ,
10 : 1 ,
17 : 1 ,
4 : 1 ,
3 : 1 ,
19 : 1 ,
11 : 1 ,
14 : 1 ,
12 : 1 ,
2 : 1 ,
9 : 1 ,
1 : 1 ,
99: 0,
6: 1,
5: 1,
16: 1
}

In [74]:
df_consolidado['TIPO_DISCAPACIDAD'].replace(dict_discapacidad, inplace=True)
df_consolidado['TIPO_DISCAPACIDAD'].unique()

array([0, 1])

In [75]:
df_consolidado.to_csv('data/2-plata/Consolidado_SIMAT_Depurado.csv')

In [76]:
df_consolidado = pd.read_csv('data/2-plata/Consolidado_SIMAT_Depurado.csv',
                             index_col=0,
                             dtype={
                                 'ANO_INF':              'uint16',
                                 'CODIGO_DANE':          'uint64',
                                 'CODIGO_DANE_SEDE':     'uint64',
                                 'TIPO_DOCUMENTO':       'uint8',
                                 'NRO_DOCUMENTO':        'string',
                                 'DIRECCION_RESIDENCIA': 'string',
                                 'RES_DEPTO':            'uint8',
                                 'RES_MUN':              'uint16',
                                 'ESTRATO':              'uint8',
                                 'SISBEN':               'float16',
                                 'GENERO':               'string',
                                 'POB_VICT_CONF':        'uint8',
                                 'PROVIENE_SECTOR_PRIV': 'string',
                                 'PROVIENE_OTR_MUN':     'string',
                                 'TIPO_DISCAPACIDAD':    'uint8',
                                 'CAP_EXC':              'uint8',
                                 'CODIGO_ETNIA':         'uint16',
                                 'CODIGO_JORNADA':       'uint8',
                                 'CARACTER':             'uint8',
                                 'CODIGO_ESPECIALIDAD':  'uint8',
                                 'CODIGO_GRADO':         'int8',
                                 'CODIGO_METODOLOGIA':   'uint8',
                                 'REPITENTE':            'string',
                                 'SIT_ACAD_ANIO_ANT':    'uint8',
                                 'CON_ALUM_ANIO_ANT':    'uint8',
                                 'ZONA_RESI_ALU':        'uint8',
                                 'EDAD':                 'uint8',
                                 'NIVEL':                'uint8',
                                 'DIR_NUM_LOCALIDAD':    'uint8',
                                 'NIVEL_SISBEN':         'uint8',
                                 'GRADO_OVERAGE':        'uint8',
                                 'OVERAGE':        'uint8'                                 
                             },
                             # Descomentar la linea de abajo si quieren que se convierta
                             # la variable 'FECHA_NACIMIENTO' a datetime
                             # parse_dates=True
                            )

/opt/conda/lib/python3.8/site-packages/numpy/lib/arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [77]:
df_consolidado

ANO_INF   CODIGO_DANE  CODIGO_DANE_SEDE  TIPO_DOCUMENTO  \
0           2017  111001000078      111001000078               2   
1           2017  111001000078      111001014834               3   
2           2017  111001000078      111001014834               3   
3           2017  111001000078      111001014834               3   
4           2017  111001000078      111001014834               3   
...          ...           ...               ...             ...   
4464566     2021  411102000293      411102000293               2   
4464567     2021  411102000293      411102000293               2   
4464568     2021  411102000293      411102000293               2   
4464569     2021  411102000293      411102000293               2   
4464570     2021  411102000293      411102000293               2   

        NRO_DOCUMENTO   DIRECCION_RESIDENCIA  RES_DEPTO  RES_MUN  ESTRATO  \
0         00010803853       CL 69 A 105 F 67         11        1        2   
1            05057637      CL 34 SUR 40 A 51         11        1        3   
2           067289989      KR 54 SUR 50 B 10         11        1        3   
3           071759788      KR 40 28 A 02 SUR         11        1        3   
4           089980482      KR 40 28 A 02 SUR         11        1        3   
...               ...                    ...        ...      ...      ...   
4464566    1012336508     KR 105 B 65 81 SUR         11        1        2   
4464567    1016713910      KR 99 A 71 39 SUR         11        1        2   
4464568    1011090034      CL 62 SUR 93 C 53         11        1        2   
4464569    1011092068    CL 61 B SUR 81 D 03         11        1        2   
4464570    1029140201  CR 82 A # 61 SUR - 30         11        1        2   

            SISBEN FECHA_NACIMIENTO GENERO  POB_VICT_CONF  \
0         0.010002       2000-01-08      F              9   
1              NaN       2012-06-13      F              9   
2              NaN       2008-10-07      M              9   
3              NaN       2012-08-23      M              9   
4              NaN       2013-11-16      F              9   
...            ...              ...    ...            ...   
4464566  54.687500       2005-09-06      F             99   
4464567  61.218750       2005-10-01      F             99   
4464568  58.218750       2005-11-30      F             99   
4464569  58.250000       2006-02-24      F             99   
4464570  57.187500       2005-01-13      F             99   

        PROVIENE_SECTOR_PRIV PROVIENE_OTR_MUN  TIPO_DISCAPACIDAD  CAP_EXC  \
0                          N                N                  0        9   
1                          N                N                  0        9   
2                          N                N                  1        9   
3                          N                N                  0        9   
4                          N                N                  0        9   
...                      ...              ...                ...      ...   
4464566                    N                N                  0        9   
4464567                    N                N                  0        9   
4464568                    N                N                  0        9   
4464569                    N                N                  0        9   
4464570                    N                N                  0        9   

         CODIGO_ETNIA  CODIGO_JORNADA  CARACTER  CODIGO_ESPECIALIDAD  \
0                   0               6         1                    5   
1                   0               3         0                    0   
2                   0               3         0                    0   
3                   0               3         0                    0   
4                   0               3         0                    0   
...               ...             ...       ...                  ...   
4464566             0               6         2                    7   
4464567             0            

# Descomentar y ejecutar para generar el dataset final

In [ ]:
# df_consolidado.to_csv('data/2-plata/Consolidado_SIMAT_Depurado.csv')